In [1]:
import os
import sys
PATH = os.getcwd()
DIR_DATA = PATH + '{0}data{0}tass{0}'.format(os.sep)
sys.path.append(PATH) if PATH not in list(sys.path) else None
DIR_DATA

'C:\\Users\\epuerta\\OneDrive - Universidad Tecnológica de Bolívar\\Apps\\courseNLP\\examples\\data\\tass\\'

## 'http://tass.sepln.org/2018/'

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from collections import Counter
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder 
from logic.text_processing import TextProcessing
from sklearn.linear_model import LogisticRegression
from imblearn.over_sampling import RandomOverSampler
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split, cross_val_score, ShuffleSplit
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import classification_report, confusion_matrix, recall_score, log_loss
from sklearn.metrics import f1_score, accuracy_score, precision_score

ModuleNotFoundError: No module named 'spacy'

In [8]:
tp = TextProcessing()
le = LabelEncoder()

Language: Text Processing
es: ['tok2vec', 'morphologizer', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']


In [9]:
data_train = pd.read_csv(DIR_DATA + 'tass2018_es_train.csv', sep=',')
data_train[:5]

tweetid           user  \
0  768213876278165504   OnceBukowski   
1  768213567418036224       anahorxn   
2  768212591105703936   martitarey13   
3  768221670255493120  endlessmilerr   
4  768221021300264964       JunoWTFL   

                                             content                 date  \
0  -Me caes muy bien \r\n-Tienes que jugar más pa...  2016-08-23 22:30:35   
1  @myendlesshazza a. que puto mal escribo\r\n\r\...  2016-08-23 22:29:21   
2  @estherct209 jajajaja la tuya y la d mucha gen...  2016-08-23 22:25:29   
3  Quiero mogollón a @AlbaBenito99 pero sobretodo...  2016-08-23 23:01:33   
4  Vale he visto la tia bebiendose su regla y me ...  2016-08-23 22:58:58   

  lang sentiment/polarity/value  
0   es                     NONE  
1   es                        N  
2   es                        N  
3   es                        P  
4   es                        N

In [10]:
data_test = pd.read_csv(DIR_DATA + 'tass2018_es_test.csv', sep=',')
data_test[:5]

tweetid           user  \
0  770976639173951488   noseashetero   
1  771092421866389508       Templelx   
2  771092111429083136       esskuu94   
3  771092070572449796     __ariadna9   
4  771094192508600320  _cristtina15_   

                                             content                 date  \
0  @noseashetero 1000/10 de verdad a ti que voy a...  2016-08-31 13:28:49   
1  @piscolabisaereo @HistoriaNG @SPosteguillo las...  2016-08-31 21:08:54   
2  Al final han sido 3h  Bueno, mañana tengo fies...  2016-08-31 21:07:40   
3  @Jorge_Ruiz14 yo no tengo tiempo para esas cos...  2016-08-31 21:07:30   
4  @_MissChaotic_ ves ese brillo? es un coso que ...  2016-08-31 21:15:56   

  lang sentiment/polarity/value  
0   es                        P  
1   es                        P  
2   es                        P  
3   es                        N  
4   es                        N

In [11]:
x_train = [tp.transformer(row) for row in data_train['content'].tolist()]
#y_train = le.fit_transform(data_train['sentiment/polarity/value'])
y_train = data_train['sentiment/polarity/value']
len(x_train), len(y_train)

(1008, 1008)

In [19]:
# x_train

In [21]:
x_test = [tp.transformer(row) for row in data_test['content'].tolist()]
#y_test = le.fit_transform(data_test['sentiment/polarity/value'])
y_test = data_test['sentiment/polarity/value']
len(x_test), len(y_test)

(506, 506)

In [23]:
bow = CountVectorizer(analyzer='word', ngram_range=(1, 3))

In [25]:
x_train = bow.fit_transform(x_train)

In [29]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [31]:
x_test = bow.transform(x_test)

In [33]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [37]:
print('**Sample train:', sorted(Counter(y_train).items()))

**Sample train: [('N', 418), ('NEU', 133), ('NONE', 139), ('P', 318)]


In [39]:
print('**Sample test:', sorted(Counter(y_test).items()))

**Sample test: [('N', 219), ('NEU', 69), ('NONE', 62), ('P', 156)]


In [51]:
k_fold = ShuffleSplit(n_splits=10, test_size=0.25, random_state=42)

In [53]:
ros_train = RandomOverSampler(random_state=1000)
x_train, y_train = ros_train.fit_resample(x_train, y_train)

In [55]:
print('**OverSample train:', sorted(Counter(y_train).items()))

**OverSample train: [('N', 418), ('NEU', 418), ('NONE', 418), ('P', 418)]


In [57]:
ros_test = RandomOverSampler(random_state=1000)
x_test, y_test = ros_test.fit_resample(x_test, y_test)

In [59]:
print('**OverSample test:', sorted(Counter(y_test).items()))

**OverSample test: [('N', 219), ('NEU', 219), ('NONE', 219), ('P', 219)]


In [61]:
softmax = LogisticRegression(multi_class="multinomial", solver="lbfgs", C=10)

In [67]:
accuracies_scores = []
recalls_scores = []
precisions_scores = []
f1_scores = []

In [69]:
for train_index, test_index in k_fold.split(x_train, y_train):
    data_train = x_train[train_index]
    target_train = y_train[train_index]
    
    data_test = x_train[test_index]
    target_test = y_train[test_index]

    softmax.fit(data_train, target_train)
    predict = softmax.predict(data_test)
    # Accuracy
    accuracy = accuracy_score(target_test, predict)
    accuracies_scores.append(accuracy)
    # Recall
    recall = recall_score(target_test, predict, average='macro')
    recalls_scores.append(recall)
    # Precision
    precision = precision_score(target_test, predict, average='weighted')
    precisions_scores.append(precision)
    # F1
    f1 = f1_score(target_test, predict, average='weighted')
    f1_scores.append(f1)

In [70]:
average_recall = round(np.mean(recalls_scores) * 100, 2)
average_precision = round(np.mean(precisions_scores) * 100, 2)
average_f1 = round(np.mean(f1_scores) * 100, 2)
average_accuracy = round(np.mean(accuracies_scores) * 100, 2)

In [73]:
average_recall

80.26

In [75]:
y_predict = []
for features in x_test:
    features = features.reshape(1, -1)
    value = softmax.predict(features)[0]
    y_predict.append(value)

classification = classification_report(y_test, y_predict)
confusion = confusion_matrix(y_predict, y_test)

In [76]:
output_result = {'F1-score': average_f1, 'Accuracy': average_accuracy, 'Recall': average_recall, 
                 'Precision': average_precision, 'Classification Report\n': classification, 
                 'Confusion Matrix\n': confusion}

In [79]:
for item, val in output_result.items():
    print('{0} {1}'.format(item, val))

F1-score 80.24
Accuracy 80.29
Recall 80.26
Precision 80.36
Classification Report
               precision    recall  f1-score   support

           N       0.35      0.69      0.46       219
         NEU       0.46      0.19      0.27       219
        NONE       0.40      0.16      0.23       219
           P       0.40      0.47      0.43       219

    accuracy                           0.38       876
   macro avg       0.40      0.38      0.35       876
weighted avg       0.40      0.38      0.35       876

Confusion Matrix
 [[151  92 118  76]
 [ 15  41  21  12]
 [ 14  12  36  27]
 [ 39  74  44 104]]
